name: Build static tools
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt install -y make wget tar curl

          # 下载官方musl交叉编译器 (aarch64)
          wget https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xf aarch64-linux-musl-cross.tgz
          sudo mv aarch64-linux-musl-cross /opt/
          echo "/opt/aarch64-linux-musl-cross/bin" >> $GITHUB_PATH

      - name: Build e2fsprogs 1.46.5
        run: |
          export CC=aarch64-linux-musl-gcc
          export CXX=aarch64-linux-musl-g++
          wget https://github.com/tytso/e2fsprogs/archive/refs/tags/v1.46.5.tar.gz
          tar -xf v1.46.5.tar.gz
          cd e2fsprogs-1.46.5
          ./configure --host=aarch64-linux-musl --enable-static --disable-shared
          make -j$(nproc)
          cp bin/e2fsck ../
          cp bin/resize2fs ../
          cd ..

      - name: Build parted-3.3
        run: |
          export CC=aarch64-linux-musl-gcc
          export CXX=aarch64-linux-musl-g++
          export CFLAGS="-Wno-implicit-function-declaration"
          wget https://ftp.gnu.org/gnu/parted/parted-3.3.tar.xz
          tar -xf parted-3.3.tar.xz
          cd parted-3.3
          ./configure --host=aarch64-linux-musl --enable-static --disable-shared
          make -j$(nproc)
          cp parted ../
          cd ..

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          path: |
            e2fsck
            resize2fs
            parted
