name: Build static e2fsprogs & parted
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install musl cross compiler
        run: |
          sudo apt update
          sudo apt install -y aarch64-linux-musl-gcc make wget tar
      - name: Compile e2fsprogs 1.46.5
        run: |
          wget https://github.com/tytso/e2fsprogs/archive/refs/tags/v1.46.5.tar.gz
          tar xf v1.46.5.tar.gz
          cd e2fsprogs-1.46.5
          ./configure --host=aarch64-linux-musl --enable-static --disable-shared
          make -j$(nproc)
          cp bin/e2fsck ../
          cp bin/resize2fs ../
      - name: Compile parted 3.2
        run: |
          wget https://ftp.gnu.org/gnu/parted/parted-3.2.tar.xz
          tar xf parted-3.2.tar.xz
          cd parted-3.2
          ./configure --host=aarch64-linux-musl --enable-static --disable-shared
          make -j$(nproc)
          cp parted ../
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          path: |
            e2fsck
            resize2fs
            parted
